# Generated by Django 3.1.5 on 2021-01-13 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(default='incorrect', max_length=7)),
                ('question2', models.CharField(default='incorrect', max_length=7)),
                ('question3', models.CharField(default='incorrect', max_length=7)),
                ('question4', models.CharField(default='incorrect', max_length=7)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
